// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcgHIQ9UQ2I78WwMehU6PP5zGJiQ7MQ0',
    appId: '1:649622728671:web:17458f3fbb362768dede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    authDomain: 'gona-d5e94.firebaseapp.com',
    databaseURL: 'https://gona-d5e94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gona-d5e94.appspot.com',
    measurementId: 'G-LG9LJXL62F',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZcgHIQ9UQ2I78WwMehU6PP5zGJiQ7MQ0',
    appId: '1:649622728671:web:e5d73d6d7eae96bedede6a',
    messagingSenderId: '649622728671',
    projectId: 'gona-d5e94',
    authDomain: 'gona-d5e94.firebaseapp.com',
    databaseURL: 'https://gona-d5e94-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gona-d5e94.appspot.com',
    measurementId: 'G-ZBYR177NVD',
  );
}
